name: platzi_store
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  quickalert: ^1.0.2
  dio: ^5.3.3
  flutter_screenutil: ^5.9.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  get_it: ^7.6.4
  blur: ^3.1.0
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9
  intl: ^0.18.0
  badges: ^3.1.2
  flutter_native_splash: ^2.2.17 m
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^2.0.0

flutter_native_splash:
  background_image: "assets/splash_screen/splash_img.jpg"
  android: true
  ios: true

flutter:  
  generate: true
  uses-material-design: true
  assets:
    - assets/splash_screen/splash_img.jpg

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  